# This configuration file is read by HTMLProofer during your CI/CD build process.

# 1. Speeds up the build process by skipping checks for external links.
disable_external: true

# 2. List of URLs/patterns to ignore during the check.
url_ignore:
  # Ignore links used for local development/testing environments (Standard Practice).
  - "/^http:\/\/127.0.0.1/"
  - "/^http:\/\/0.0.0.0/"
  - "/^http:\/\/localhost/"
  
  # CRITICAL FIX: These lines ignore the scripts that contain a query string 
  # (like '?baseurl=...') used by themes (e.g., Chirpy) for cache busting. 
  # HTMLProofer incorrectly flags these URLs as missing assets.
  - "/assets/js/dist/app.min.js?"
  - "/assets/js/dist/theme.min.js?"

# 3. Ensures no file-level ignores conflict with url_ignore.
ignore_files: []